### ISSUE TITLE
Migrating to Go Modules

### ISSUE THREAD

**Issue by afdesk** [aquasecurity/postee#108]
This project started a few years ago, when Go didn't support modules and it uses make for building.
Now Go versions use modules by default.

I suggest to migrate from `make` to `go modules`.

The code will become more clearer and modern.
also for me it'll be more convenient to use code from Postee into UI. 

@jerbia, @krol3 What do you think about this migration?

**Comment by krol3** [comment]
Love it the idea.  Already I had a older pr to migrate it.  I could help with the migration if you can @afdesk

**Comment by afdesk** [comment]
@krol3 Great thanks! your help will need!

I want to run `go mod init` and change dependencies.
After it it'd be nice if you update deployment scripts.
thanks!

**Comment by afdesk** [comment]
@krol3 I've made major changes, pushed `issue-108` branch and the draft PR was broken.

Can you take a look at it? 
Thanks!

**Comment by krol3** [comment]
I will take a look today @afdesk
