### ISSUE TITLE
Postee fails to send email to application scope owner

### ISSUE THREAD

**Issue by lorsal** [aquasecurity/postee#111]
When configuring Postee to send email notifications to the respective application scope owners by including "<%application_scope_owner%>" in the list of recipients in the config map, the postee server log shows an error and the results are not sent. 

2021/04/08 11:17:12 get application scope owners error for "ses": recipients field contains "<%application_scope_owner%>", but received a webhook without this data

It does work when entering a specific email address in the config map. 

Recipients were listed in the config map in the following format: 
recipients: ["<%application_scope_owner%>"]

**Comment by afdesk** [comment]
@lorsal thank you for your feedback and details! 

I'm reviewing the scan results from your log file, and I can't find `application_scope_owners` field in these webhooks.

**Comment by afdesk** [comment]
`<%application_scope_owner%>` means that `Postee` will send the email to the image application scope owners (as defined in the Application Scope assigned to the image). 
@lorsal Could you check these settings? thanks!

**Comment by jerbia** [comment]
@lorsal Did you create an Application Scope in the Aqua UI?

See attached screenshot for an example of Application Scope that will trigger Postee to send email to xx@xx.com once an Alpine image is scanned.

![image](https://user-images.githubusercontent.com/3126261/114031201-cea52800-9883-11eb-90b0-ab9b38dcdd12.png)

**Comment by lorsal** [comment]
Hi, thank you for the quick replies!

I did create an application scope with my email address (as in your screenshot @jerbia )

I just tried again with a different namespace (and application scope), please find the server logs attached.

[server.log](https://github.com/aquasecurity/postee/files/6278963/server.log)

**Comment by afdesk** [comment]
@lorsal 
Could you show `Postee` logs? but **without** blocks: `alertmgr.PluginSettings{Name:""...`

**Comment by lorsal** [comment]
Here you go
[postee-log-2.txt](https://github.com/aquasecurity/postee/files/6279098/postee-log-2.txt)

**Comment by afdesk** [comment]
@lorsal I'm trying to debug this issue. and I don't see `application_scope_owners` field in your logs.

My steps for reproducing the issue are next:
1. In Aqua UI: go to `Administration` -> `Application Scopes`
2. Add Scope (or edit an existing scope)
3. Add `Owner Email`
4. Add `Repository` into `Artifacts`
5. Click `Update`
6. Rescan a specific image from the scope

And I receive a correct webhook with `application_scope_owners`

@lorsal Did you go the same way?

**Comment by lorsal** [comment]
Ah yes, I just tried the Artifacts variant (your step 4) and that works. What I was trying to do earlier (and what we need) is to add a namespace under the Workloads section and then send the email to the owner. 
I didn't realize that you need to combine the two (fill in Artifacts and Workloads).
Anyway, it works now. Thank you!

**Comment by afdesk** [comment]
@lorsal I was glad to help you!
Can we close this issue?
