### ISSUE TITLE
Application Scope Owner error when using Aggregate-Issues-Timeout

### ISSUE THREAD

**Issue by lorsal** [aquasecurity/postee#122]
When including the Aggregate-Issues-Timeout flag in the Config Map, Postee throws a "get application scope owners" and says that the webhook does not contain that data. The logs show that the scan results do contain the email address.

Upon removing the Aggregate-Issus-Timeout flag from the Config Map and restarting the Postee pod, the email function works as expected. When the same images are scanned in Aqua, the results are forwarded to Postee and emails are sent out.

**Comment by jerbia** [comment]
@afdesk can you look at this issue?

**Comment by jerbia** [comment]
@lorsal can you
