### ISSUE TITLE
Introduce versioning for postee

### ISSUE THREAD

**Issue by janblahovec** [aquasecurity/postee#123]
Hello everybody,

would it be possible to introduce versioning of postee images - versions e.g. 1.0

Thanks a lot!

Cheers,
Jan

**Comment by jerbia** [comment]
@krol3 can you help with this? Once we release a new Postee it needs to be tagged with the release version.

**Comment by krol3** [comment]
Yeah I could help with that @jerbia. I will work in the issue

**Comment by janblahovec** [comment]
This seems to be resolved,
(https://github.com/aquasecurity/postee/releases/tag/v1.1.4)
so thanks a lot !

Cheers, 
Jan
