### ISSUE TITLE
Send a MS teams webhook based on Application scope

### ISSUE THREAD

**Issue by janblahovec** [aquasecurity/postee#126]
Hello,

I have several application scopes in Aquasec. And what I want to achieve -> After scan of concrete image I would like to use ms teams webhook to notify concrete MS teams channel.

Let say I have these application scopes - AS A, AS B, AS C
and these MS teams channels - Channel A, Channel B, Channel C

So after scan of some image which belongs to the AS A I would like to notify the results with Webhook Channel A in MS Teams.

Would it be possible?

Thanks a lot

Best regards,
Jan

**Comment by jerbia** [comment]
Hi @janblahovec you can do the following:

1. Create multiple "MS Teams" entries in the cfg.yaml. Each pointing to different URL.
2. For each entry, add the "Policy-OPA" predict and point it to a different REGO file. 
3. The REGO file will have a Rego expression that checks that the input payload have a specific application scope owner email.
See below example REGO policy:

package postee
default allow = false
allow {
input.application_scope_owners[_] = "<put email address of owner of application scope>"
}

As a result - when an image is scanned, Aqua will send the scan payload to Postee. 
Postee will check against all the entries in cfg.yaml for a match in the "Policy-OPA" Rules. 
If there is a match - it will send the scan details only to the entry in cfg.yaml that had the match.

Hope this helps.

**Comment by janblahovec** [comment]
Hi @jerbia 

Ok thanks for the info, I will try.

I started with settuping simple MS Teams webhook integration (
- name: ms-team
  type: teams
  enable: true
  url: https://... <url to my webhook in ms teams>
  )

and when I scan some image in aquasec (as you described in docu) and check the logs in container, I still got this issue:

(some logs)
2021/04/26 12:44:03 Sending to MS Teams via "ms-team"...
...
2021/04/26 12:44:03 Length of Description for "ms-team": 2737/18000
2021/04/26 12:44:03 MS Team plugin will send LONG message
2021/04/26 12:44:03 Message is: ...(message)
**2021/04/26 12:44:03 TeamsPlugin Send Error: Post "url to my webhook": EOF**

Do you know what could be the issue?

Thanks a lot

**Comment by afdesk** [comment]
Hi @janblahovec, sorry for the  inconvenience.
I'm testing it now.
thanks!

**Comment by janblahovec** [comment]
Hi @afdesk, never mind. 
Thanks a lot for a quick answer!
Cheers, 
Jan

**Comment by afdesk** [comment]
@janblahovec we're tryiing to reproduce your problem. But I've not gotten an error (`EOF`) yet.

We did next:
1. Create a new webhook: [Add an incoming webhook to a Teams channel](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook)
2. My config:
```yaml
- name: new-channel-msteam
  type: teams
  enable: true
  url: https://...webhook.office.com/webhookb2/....
```
3. Rescan,

also, is it possible to check an access to your MS Teams instance via `curl`?
```sh
curl -H 'Content-Type: application/json' -d '{"text": "Test messase"}' <YOUR WEBHOOK URL>
```
Thanks!

**Comment by janblahovec** [comment]
@afdesk posting message with curl to the teams channel was successfully

I will try to create a new channel and new config with fresh postee deployment.

I will let you know asap.

Jan

**Comment by afdesk** [comment]
@janblahovec thanks for your help!

**Comment by janblahovec** [comment]
@afdesk still the same results :( 

I created new msteams channel, new connector, copied created url from that connector to the cfg.yaml, then I did pure new deployment of postee
my cfg.yaml

---
- type: common   #  Common settings for all plugins
  AquaServer: https://...url of my server  
  Max_DB_Size: 1000   #  Max size of DB. MB. if empty then unlimited
  Delete_Old_Data: 10   #  delete data older than N day(s).  If empty then we do not delete.
  DbVerifyInterval: 1   #  hours. an Interval between tests of DB. Default: 1 hour

- name: ms-team
  type: teams
  enable: true
  url: https://....webhook.office.com/webhookb2/....

then I scan some image from Aquasec console
and result is: (logs from postee container)
2021/04/28 10:22:22 Webhook for "ms-team": "https://....webhook.office.com/webhookb2/...."
2021/04/28 10:22:22 Length of Description for "ms-team": 2662/18000
2021/04/28 10:22:22 MS Team plugin will send LONG message
2021/04/28 10:22:22 Message is: "...message..."
2021/04/28 10:22:22 TeamsPlugin Send Error: Post "https://....webhook.office.com/webhookb2/....": EOF

**Comment by afdesk** [comment]
@janblahovec Oh, i see, thanks. will try again.

**Comment by afdesk** [comment]
@janblahovec  I have a new idea )
Which postee release do you use? An Image from Docker hub?
thanks

**Comment by janblahovec** [comment]
@afdesk yes [docker.hub](https://hub.docker.com/layers/aquasec/postee/latest/images/sha256-a6cc4bb14824387323be5a4ee9adbc3f34d6c96b9751d464a7f849cf26d90a61?context=explore) this one.

**Comment by janblahovec** [comment]
@afdesk and I am using helm chart for the deployment

**Comment by afdesk** [comment]
@janblahovec does this error pop up for any scans/repositories? could you give me an image name, for example?
Great thanks!

**Comment by janblahovec** [comment]
@afdesk the same error is for all scans -> some of scans are triggered by me, some are automatically triggered.
our images are stored in AWS ECR.

**Comment by afdesk** [comment]
Hi @janblahovec 
I don't have any ideas yet.
maybe can we schedule a call to understand this issue?
is it possible for you?
thanks!

**Comment by janblahovec** [comment]
Hi @afdesk, I did not find time to test connection from container. (send curl to msteams)
At first I would like to test it, and if it will not be working, I will write you.
Is it ok for you?
Many thanks

Jan

**Comment by afdesk** [comment]
@janblahovec sure, I'll wait.
thanks!

**Comment by janblahovec** [comment]
Hi @afdesk!
I have good news.
I deployed postee to our playground environment and it started working. So probably we have something differently configured in our production environment.

Thanks for your time and support.
Best regards
Jan

**Comment by afdesk** [comment]
Hi @janblahovec 
I'm glad to read it!
Can we close this issue?

**Comment by janblahovec** [comment]
Hi @afdesk,
please not yet. At first I would like to also test sending notifications to different channels based on application scopes. ( with rego policies)

**Comment by janblahovec** [comment]
Hello @jerbia  and @afdesk !

Thanks a lot for your help.
I tested it and it is working like a charm!
So, I am closing the issue.

Have a nice day.
Best regards,
Jan
