### ISSUE TITLE
Postee resource limits

### ISSUE THREAD

**Issue by amitaqua** [aquasecurity/postee#129]
Hi There,
Can you specify what are the Tracee resource limits with regards to CPU and memory?
These limits are needed as we would like to run Tracee on a Kubernetes environment which requires these limits. 

Tnx & Regards,

Amit.

**Comment by jerbia** [comment]
@afdesk can you please look at this? I suggest running Postee with simulated stress (100's of requests per second) and examining its growth in CPU and memory.

**Comment by afdesk** [comment]
@jerbia sure, I'll do it.

**Comment by afdesk** [comment]
@amitaqua 
we recommend to set next limits: 256mb or Memory and 500mi for CPU.

**Comment by amitaqua** [comment]
@afdesk tnx, what should we set as requests?

**Comment by afdesk** [comment]
@amitaqua I didn't understand the question a little. do you mean a link for webhooks?

**Comment by afdesk** [comment]
@amitaqua sorry, my mistake.
we offer to set next `requests`: 128MB for memory and 200Mi for CPU.

**Comment by amitaqua** [comment]
@afdesk thank you very much.

**Comment by afdesk** [comment]
@amitaqua no problem. can we close this issue?

**Comment by amitaqua** [comment]
@afdesk sure - thank you
