### ISSUE TITLE
Send notification when Drift prevention was found

### ISSUE THREAD

**Issue by janblahovec** [aquasecurity/postee#132]
Hello!

I have one question regarding [Aquasec Drift prevention](https://blog.aquasec.com/cloud-native-security-drift-prevention) and Postee. 
Does Postee support this feature? So, basically when someone will try to run some own script in running container, could then Postee send a notification?
If there is the way how to do it, please let me know.

Many thanks.
Have a nice day

Jan

**Comment by janblahovec** [comment]
Hi @jerbia, thanks a lot for an info.
I am looking forward to next release.
Cheers,
Jan

**Comment by janblahovec** [comment]
Hello @jerbia,
Any updates on this issue?
Thanks,
Jan

**Comment by jerbia** [comment]
We are in the process of merging Postee v2. It's a very big change therefore takes a bit time to finish.

If you want you can try out the v2 branch here:
https://github.com/aquasecurity/postee/tree/v2

**Comment by janblahovec** [comment]
OK, thanks a lot for the info. Fingers crossed!

Best regards,
Jan

**Comment by jerbia** [comment]
@janblahovec Postee 2.0 was relesae today. Plese try it out and let us know if there are issues.

**Comment by janblahovec** [comment]
Hello @jerbia!
I have one question - is this functionality implemented?
Is there any sample/tutorial what needs to be configured in Postee? I would like to receive notification to my MS Teams channel when this situation happens.
Many thanks!
Cheers,
Jan
