### ISSUE TITLE
Postee db path is relative

### ISSUE THREAD

**Issue by roeeliv** [aquasecurity/postee#141]
```
ScanService.Init Error: Can't init service with data: {...}
Error: open /server/database/webhooks.db: no such file or directory
```
The above error appears to be related to our DbPath variable which is being used on BoltDB Open operations. The Open operation requires an absolute path, while currently relative paths are used. Relative path/file creations are prone to errors such as the one above, when the relative path provided doesn't exist.

**Comment by afdesk** [comment]
it seems like this issue is the same as #145.
I missed a creation of the default folder for db during auto deploy.
The hot fix is using an external volume for db folder.
```
-v /path/on/host/database-folder/:/server/database/
```

**Comment by AndreyLevchenko** [comment]
@jerbia @afdesk 
The default folder for db is created now
https://github.com/aquasecurity/postee/blob/main/Dockerfile.release#L6
So I think issue can be closed
