### ISSUE TITLE
unable to report to JIRA after scanning images with aqua

### ISSUE THREAD

**Issue by guyyakir** [aquasecurity/postee#145]
when running postee 1.1.4/ 1.1.3 after Aqua finish the scanning, postee is unable to integrate with JIRA.
the error is "Error: open /server/database/webhooks.db: no such file or directory "

postee seems to not be creating the directories in those images. when running postee latest/1.1.2 everything works fine

**Comment by jerbia** [comment]
@afdesk can you look at this?

**Comment by afdesk** [comment]
@guyyakir thanks
I'll test to mean what we lost. 
it's really strange bug, because for `1.1.4/ 1.1.3` were changed only goreleaser settings.

**Comment by afdesk** [comment]
I've reproduced this issue. try to fix it.

**Comment by afdesk** [comment]
It seems like I missed a creation of the default folder for db during autodeploy.
The hot fix for this issue is using an external volume for db.
```
-v /path/on/host/database/:/server/database/
```

**Comment by jerbia** [comment]
@afdesk is this issue still relevant in postee 2.0? Can we close it?

**Comment by AndreyLevchenko** [comment]
@guyyakir 
Does @afdesk  suggestion work out? Can issue be closed?

**Comment by jerbia** [comment]
Closing the issue for now.
