### ISSUE TITLE
Unable to Assign Issue Assignee to On Premise Jira

### ISSUE THREAD

**Issue by qhe6** [aquasecurity/postee#158]
The Ticket are created by Aqua Postee, yet the assignee cannot be assigned. 
The assignee info are configured in the cfg.yml 

1. **Does Postee support on Premise Jira Server ?**

2. **The User Search api for Jira Cloud is not applicable to Jira Server.**  Which API does
https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-user-search/#api-rest-api-2-user-search-query-get
https://docs.atlassian.com/software/jira/docs/api/REST/8.5.5/#api/2/user-findUsers

`GET /rest/api/2/user/search/query` resulting error when sending to the on premise Jira.
![image](https://user-images.githubusercontent.com/88829046/129321945-e7c0e681-80b9-48ef-b1eb-d663def4bfe8.png)
   For the assign issue api, they share the same api.
   https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issues/#api-rest-api-2-issue-issueidorkey-assignee-put
   https://docs.atlassian.com/software/jira/docs/api/REST/8.5.5/#api/2/issue-assign

**Comment by jerbia** [comment]
@qhe6 can you check the latest Postee "main" branch?
