### ISSUE TITLE
button test in input rego rule 

### ISSUE THREAD

**Issue by krol3** [aquasecurity/postee#176]
It will be a nice feature, to put a button for testing the REGO rule in the postee-UI

See the screenshot 

<img width="890" alt="Screen Shot 2021-09-24 at 14 15 41" src="https://user-images.githubusercontent.com/8355621/134715089-53314610-3323-4194-8c04-ff1e3474b151.png">

**Comment by jerbia** [comment]
Part of release 2.0.6
