### ISSUE TITLE
Postee Integration with Jira Software

### ISSUE THREAD

**Issue by NSSG-WEI** [aquasecurity/postee#181]
Hi community,

I am doing an integration testing btw Postee and Jira Software and the objective is to send the image scanned result to Jira.

### Environment Info
- Aqua Web and Aqua Postee are deployed in OpenShift OCP v4.6
- Jira Software (Data Center Edition) v8.19.0 (on-prem)

All mentioned components are successfully deployed and has configured the Aqua Server - Image Scan Results Webhook to point to the Aqua Postee
([https://github.com/aquasecurity/postee#configure-the-aqua-server-with-webhook-integration](url))

On the Jira end, I have provisioned a user and generated a personal access token for the integration.
(Reference to the following screenshots)

<img width="544" alt="Jira Generate Token - 01" src="https://user-images.githubusercontent.com/52770697/136317453-eaa01956-1997-45c0-a62d-732586fb06f2.png">
<img width="636" alt="Jira Generate Token - 02" src="https://user-images.githubusercontent.com/52770697/136317509-3d19a817-3fc7-4414-8435-9d00fe34e84c.png">

I have input the username and Personal Access Token in the postee-cm.yaml file
([https://github.com/aquasecurity/postee/tree/main/deploy/kubernetes](url)) according to the Jira Integration Parameters as described in: [https://github.com/aquasecurity/postee#jira-integration-parameters](url)

I tested the integration by triggering an image scanning from Aqua Server thus the webhook notification will be sent to Aqua Postee and eventually create an issue in the Jira.

### Encountered Issue
- The integration is not successful as I have encountered an 403 (Forbidden) error
- In the Aqua Postee logs, it mentioned failed to get board from Jira
- 401 (Unauthorized) error is observed

Initially, I thought that I have supplied the wrong Personal Access Token thus, I manually perform a REST call to the Jira using curl command and using the generate Personal Access Token
- The curl command went through successfully
- It proves that the generated Personal Access Token has no issue

### Observation
- I replaced the Personal Access Token with the password of the user in the postee-cm.yaml
- Redeployed the Aqua Postee component and the integration goes through successfully
- The image scan result is successfully sent over to Jira

It seems like Personal Access Token is not supported from my observation/testing

### Clarification
1) Anyone know the supported Jira products and versions for Aqua Postee integration with Jira

2) Is Personal Access Token supported for Aqua Postee integration with Jira?
- Based on the URL: [https://github.com/aquasecurity/postee#jira-integration-parameters](url) , it stated the password filed refers to user's API key
- Isn't Personal Access Token considered a user's API key?

3) If Personal Access Token is not supported and only supports user's password to be input in the cfg.yaml, the password will be shown as clear text. Any way to secure the clear text password?

Hope anyone in the community has similar experience and encounters can point me to the right direction, thank you.

**Comment by AndreyLevchenko** [comment]
Hi @NSSG-WEI 
I was able to re-produce issue. On-premise Jira handles PAT a bit different way. I'm working on fix

**Comment by NSSG-WEI** [comment]
@AndreyLevchenko ,
Thanks for the confirmation on the bug and working on the fix. 

Besides fixing the handling of PAT in postee, is there any way to handle the clear text password in the cfg.yaml?

**Comment by NSSG-WEI** [comment]
@AndreyLevchenko ,

For the fix for on-prem Jira handling PAT, will it be released soon?

**Comment by AndreyLevchenko** [comment]
Hi @NSSG-WEI 
Plan is to release this or next week

**Comment by NSSG-WEI** [comment]
@AndreyLevchenko,

Based on the feedback previously, the fix for on-prem Jira handing PAT, is it already released?

**Comment by krol3** [comment]
Yes! @NSSG-WEI  could you test it? is it resolved?

**Comment by NSSG-WEI** [comment]
I have tested, the mentioned issue is resolved.

I realized the postee image (Able to handle to PAT) is not yet push into the aquasec registry,  will it be pushed to aquasec registry eventually?
- As of current, I built the postee image based on the following docker file:
https://github.com/aquasecurity/postee/blob/main/Dockerfile

**Comment by jerbia** [comment]
Done. We've just published Postee release 2.0.6
