### ISSUE TITLE
Route docs Issue

### ISSUE THREAD

**Issue by raesene** [aquasecurity/postee#183]
while configuring Tracee and Postee, I noticed that if I follow the docs at https://github.com/aquasecurity/postee/blob/main/docs/routes.md and use this for my route

```
input: contains(input.SigMetadata.ID,"TRC-")
```
I get errors

```
Error while evaluating rego rule input: contains(input.SigMetadata.ID,"TRC-") :1 error occurred: 1 error occurred: postee.rego:6: rego_parse_error: unexpected : token: expected \n or ; or }
        input: contains(input.SigMetadata.ID,"TRC-")
```

removing the `input:` from the start fixes it, should we updated the docs for that?

**Comment by krol3** [comment]
@jerbia  we could create a documentation page about cfg.yaml. 
When we use the config file, we will need `input:`. https://github.com/aquasecurity/postee/blob/main/cfg.yaml#L17
When we use the postee-UI we don't need it. I think so. 

@raesene  could you confirm if you use the postee-UI or the cfg.yaml ?

**Comment by AndreyLevchenko** [comment]
@jerbia, @krol3, @raesene   
from what I can understand `input: ` is part of yaml structure. UI parses yaml so everything from yaml properties goes to corresponding fields
