### ISSUE TITLE
Report with encoding text in the report

### ISSUE THREAD

**Issue by krol3** [aquasecurity/postee#203]
In the detail of the email report, I can observe encoding text:

`See more: [Docker Hub/alpine%3A3.9.6]Docker Hub/alpine%3A3.9.6`

![Screen Shot 2021-11-17 at 22 18 36](https://user-images.githubusercontent.com/8355621/142333413-c9e08776-3ba2-4e1e-bd89-f80520411bb5.png)

Same case using MsTeams

![Screen Shot 2021-11-18 at 09 48 47](https://user-images.githubusercontent.com/8355621/142418293-f7a2f540-e792-4223-9f84-4ee9677f23e3.png)

**Comment by jerbia** [comment]
@AndreyLevchenko  @afdesk  can you look at this?

**Comment by AndreyLevchenko** [comment]
Hi @krol3 
What type of template are you using?

**Comment by krol3** [comment]
> Legacy template. Using the default values of the sample deploy in Kubernetes.
https://github.com/aquasecurity/postee/blob/main/deploy/kubernetes/postee.yaml#L39

![Screen Shot 2021-11-30 at 20 21 15](https://user-images.githubusercontent.com/8355621/144143802-3c3d5c20-1da9-49db-bac4-7d640bf094f3.png)
