### ISSUE TITLE
Aquasec Drift Prevention - question

### ISSUE THREAD

**Issue by janblahovec** [aquasecurity/postee#205]
Hello @jerbia!
I have one question - is this functionality implemented in Postee V2?
Is there any sample/tutorial what needs to be configured in Postee? I would like to receive notification to my MS Teams channel when this situation happens.
Many thanks!
Cheers,
Jan

see: https://github.com/aquasecurity/postee/issues/132

**Comment by jerbia** [comment]
Please see the following:

https://github.com/aquasecurity/postee/blob/main/docs/routes.md#route-drift-prevention-messages

**Comment by jerbia** [comment]
I've also created a sample cfg file for configuration of MS Teams for Drift Prevention messages:
https://github.com/aquasecurity/postee/blob/main/docs/examples/drift-teams.yaml
