### ISSUE TITLE
postee-ui build is failing

### ISSUE THREAD

**Issue by poggenpower** [aquasecurity/postee#235]
when starting a postee stack via "docker compose up" the build of postee-ui is failing:

 > [postee_posteeui gobuilder 4/4] RUN go build -o posteeui:
#38 10.30 go: github.com/aquasecurity/postee@v1.1.5-0.20211210093651-b669cce16033 requires
#38 10.30 	github.com/open-policy-agent/opa@v0.35.0 requires
#38 10.30 	github.com/dgraph-io/badger/v3@v3.2103.2 requires
#38 10.30 	golang.org/x/net@v0.0.0-20201021035429-f5854403a974 requires
#38 10.30 	golang.org/x/crypto@v0.0.0-20200622213623-75b288015ac9: missing go.sum entry; to add it:
#38 10.30 	go mod download golang.org/x/crypto
------

https://pkg.go.dev/golang.org/x/crypto?tab=versions doesn't list the version at all. Not sure what happens with the version referenced above.

**Comment by poggenpower** [comment]
Seems using the latest version of `github.com/open-policy-agent/opa@v0.36.1` fixes the issue

**Comment by AndreyLevchenko** [comment]
Hi Tomas
Thank you for your investigation.
We've got open PR for fixing it (#232)
I'm going to handle the issue today

**Comment by AndreyLevchenko** [comment]
@poggenpower 
I've merged #234 which can resolve issue. Please test if it resolves issue for you and let me know results

Thanks
Andrey
