### ISSUE TITLE
feature: Use sane timeouts for HTTP Client

### ISSUE THREAD

**Issue by simar7** [aquasecurity/postee#237]
Currently webhook output uses a default HTTP Client which doesn't have a timeout defined: https://github.com/aquasecurity/postee/blob/main/outputs/webhook.go#L32

This means no timeout and blocking calls. We should set this to a sane value.

**Comment by DmitriyLewen** [comment]
Hello @simar7 
Thank you for your issue!
It is good idea!
I will do it soon.

Regards, Dmitriy
