### ISSUE TITLE
Aqua image scan result - running image

### ISSUE THREAD

**Issue by janblahovec** [aquasecurity/postee#253]
Hello there!

I would like to ask you one thing regarding result JSON, which is input for Postee (json which is generated after image scan in Aquasec) .
Is there a possibility / exist there a way how to know, that image which was scanned is currently running in cluster?

My idea is - send notification of scans to users for images which are currently running in the cluster.

Many thanks!

Cheers,
Jan

**Comment by simar7** [comment]
hi @janblahovec - thanks for the your question. Are you looking to make decision (send notification to users) based on the scans results that Postee receives?

**Comment by janblahovec** [comment]
Hi @simar7, yes

**Comment by simar7** [comment]
Good question! We're actually working on a feature right now that should allow a security practitioner like you to bring in outputs that are customizable. 

The feature is called Postee Actions and should allow you to bring in configurable outputs such as shell scripts or custom http calls that can be triggered in a use case like yours (scan an image and take an action)

If you'd like to give feedback here's the current design and PR https://github.com/aquasecurity/postee/pull/249

Thanks!

**Comment by janblahovec** [comment]
Or maybe.. I want to send results of a scan to some user (MS TEAMS channel) only for scanned image, which is currently running in cluster. 
I want to somehow have this information in that result json/ or know based on which argument/what I know that this concrete scanned image is currently running in the cluster

Thanks

**Comment by simar7** [comment]
IIUC, you could create a custom rego template for your use case to include the information you want - an example: https://github.com/aquasecurity/postee/blob/main/rego-templates/example/audit-html.rego

Docs: https://github.com/aquasecurity/postee#customizing-templates

**Comment by simar7** [comment]
Please let us know if you still require help by reopening this issue. Thanks!
