### ISSUE TITLE
Jira integration with Postee failing with error: Failed to init issue: key Priority is not found in the list of fields

### ISSUE THREAD

**Issue by AquaOms** [aquasecurity/postee#255]
Jira integration with Postee failing with error: Failed to init issue: key Priority is not found in the list of fields, however the "priority" key is on the list. please see config and logs below:

#### Routes are used to define how to handle an incoming message
routes:
- name: my-jira
  outputs: [ my-jira ]
  template: legacy-jira

...............

- name: my-jira # name must be unique
  type: jira # supported types: jira, email
  enable: true
  url: "http://***********/jira" # Mandatory. E.g "https://johndoe.atlassian.net"
  user: ******** # Mandatory. E.g :johndoe@gmail.com"
  password: ******** # Optional. Specify Jira user API key. Used onlyfor Jira Cloud
  token: # Optional. Specify Jira user Personal Access Token. Used only for Jira Server/Data Center
  project-key: ****** # Mandatory. Specify the JIRA product key
  tls-verify: false
  board: AQUA2 # Optional. Specify the Jira board name to open tickets on
  labels: ["Aqua", "SecOps"] # Optional, specify array of labels to add to Ticket, for example: ["label1", "label2"]
  priority: Высокий     # Optional. Specify the issues severity. Default is "High"
  assignee: # Optional. Specify the assigned user. Default is the user that opened the ticket
  description: # Optional.
  issuetype: Задача # Optional. Specifty the issue type to open (Bug, Task,etc.). Default is "Task"

Notes: Customer uses Russian jira, so some of the fields are in Russian. For example, the "issuetype" and "priority" field.

Logs after run:

2022/01/21 11:12:53 Starting Router....
2022/01/21 11:12:53 Loading alerts configuration file /config/cfg.yaml ....
2022/01/21 11:12:53 Configuring template vuls-slack
2022/01/21 11:12:53 Configured with Rego package postee.vuls.slack
2022/01/21 11:12:53 Configuring template vuls-html
2022/01/21 11:12:53 Configured with Rego package postee.vuls.html
2022/01/21 11:12:53 Configuring template raw-html
2022/01/21 11:12:53 No aggregation package configured!!!
2022/01/21 11:12:53 Configured with Rego package postee.rawmessage.html
2022/01/21 11:12:53 Configuring template legacy
2022/01/21 11:12:53 Configured with legacy renderer html
2022/01/21 11:12:53 Configuring template legacy-slack
2022/01/21 11:12:53 Configured with legacy renderer slack
2022/01/21 11:12:53 Configuring template legacy-jira
2022/01/21 11:12:53 Configured with legacy renderer jira
2022/01/21 11:12:53 Configuring template custom-email
2022/01/21 11:12:53 Configuring template raw-json
2022/01/21 11:12:53 No aggregation package configured!!!
2022/01/21 11:12:53 Configured with Rego package postee.rawmessage.json
2022/01/21 11:12:53 Output stdout is configured
2022/01/21 11:12:53 using board ID 961 with Name "AQUA2"
2022/01/21 11:12:53 Starting Jira output "my-jira"....
2022/01/21 11:12:53 Output my-jira is configured
2022/01/21 11:12:53 Starting WebServer....
2022/01/21 11:12:53 Listening for HTTPS on 0.0.0.0:8444
2022/01/21 11:12:53 Listening for HTTP on 0.0.0.0:8084

And logs after scan:

2022/01/21 11:13:35 route "my-jira" is associated with template "legacy-jira"
2022/01/21 11:13:35 Failed to init issue: key Priority is not found in the list of fields
2022/01/21 11:13:35 Error while sending event: key Priority is not found in the list of fields
2022/01/21 11:13:36 route "my-jira" is associated with template "legacy-jira"
2022/01/21 11:13:36 Failed to init issue: key Issue Type is not found in the list of fields
2022/01/21 11:13:36 Error while sending event: key Issue Type is not found in the list of fields 

Please share with me whether Russian is supported in the "priority" key or whether the issue is elsewhere.

**Comment by simar7** [comment]
@DmitriyLewen could you take a look at this?

**Comment by DmitriyLewen** [comment]
Hello @simar7 , @AquaOms 
I checked this problem. 
Postee does not support Russian language jira.
Postee uses English field names that do not match Russian names. 

Regards, Dmitriy

**Comment by AndreyLevchenko** [comment]
we should call an API to get jira issue fields config first and then pick configured field names to account localization

**Comment by simar7** [comment]
Thanks @DmitriyLewen, I wasn't aware of the difference in the field names when it comes to localization of JIRA.

@AndreyLevchenko - that sounds like a good idea. Since this currently prevents the user from using Postee, could you work on it?

**Comment by simar7** [comment]
hi @AquaOms - the new v2.2.0 release should include support for non English JIRA's. Please re-open or reach out if you're still facing an issue. Thanks!
