### ISSUE TITLE
Upload a transparent Postee logo

### ISSUE THREAD

**Issue by YuviGold** [aquasecurity/postee#256]
The https://github.com/aquasecurity/postee/blob/main/postee.jpeg logo that's shown in the [README](https://github.com/aquasecurity/postee/blob/main/README.md) has a white background. For browsers that have a dark mode, it looks a bit weird.

![Screenshot from 2022-01-31 17-49-49](https://user-images.githubusercontent.com/29873449/151827065-e88606da-ab51-475a-84e5-591778a80c41.png)

I was trying to change it with the uploaded `postee.jpg` but it's a low-quality file (13KB).

An example of [trivy](https://github.com/aquasecurity/trivy/blob/main/README.md)'s logo supporting dark mode
![Screenshot from 2022-01-31 17-57-42](https://user-images.githubusercontent.com/29873449/151827826-2754988a-aff2-447b-bef0-42f44a4bab98.png)

**Comment by simar7** [comment]
hi @YuviGold - thanks for the report, we'll look into it.

**Comment by simar7** [comment]
Logo is now updated
