### ISSUE TITLE
Customization of scan report email subject

### ISSUE THREAD

**Issue by lorsal** [aquasecurity/postee#261]
We use Postee v2 to send scan report emails to application teams and would like to customize the email subject line. Is that doable?
Thank you.

**Comment by simar7** [comment]
hi @lorsal - today the subject is the `content` key in the event that Postee receives and is not user configurable. 

Is this an urgent need for you? If so we can look into adding it as a feature.

**Comment by AndreyLevchenko** [comment]
If Postee v2 is used with Rego templates then title can be customized
for vul_html template it's configured here:
https://github.com/aquasecurity/postee/blob/main/rego-templates/vuls-html.rego#L164

**Comment by simar7** [comment]
thanks @AndreyLevchenko - so just to clarify you're saying that @lorsal could define a custom template like the one above with a different title?

**Comment by lorsal** [comment]
@AndreyLevchenko @simar7 Yes, that is what I was looking for, thanks guys.
