### ISSUE TITLE
PosteeUI depends on old postee version v1.1.5-0.20211210093651-b669cce16033

### ISSUE THREAD

**Issue by poggenpower** [aquasecurity/postee#264]
https://github.com/aquasecurity/postee/blob/main/ui/backend/go.mod#L6

PosteeUI should depend on/require latest postee version to take advantages of latest changes and bugfixes. 

Versioning of postee itself seems to be out off order.

```
❯ go get github.com/aquasecurity/postee@63f61289a222bc1dae6232a1cc2f804c3b62c501
go get github.com/aquasecurity/postee@63f61289a222bc1dae6232a1cc2f804c3b62c501: github.com/aquasecurity/postee@v1.1.5-0.20220121150315-63f61289a222: invalid version: go.mod has post-v1 module path "github.com/aquasecurity/postee/v2" at revision 63f61289a222
```

**Comment by simar7** [comment]
Good catch - we should pin it to the next released version unless there is some other reason to keep it pinned at this? cc @AndreyLevchenko / @afdesk ?

**Comment by poggenpower** [comment]
Please review https://github.com/aquasecurity/postee/pull/272

**Comment by poggenpower** [comment]
Need this change first to post a fix for https://github.com/aquasecurity/postee/issues/268

**Comment by simar7** [comment]
Closing as https://github.com/aquasecurity/postee/pull/272 is merged
