### ISSUE TITLE
update go version in docker files and posteeUi go.mod

### ISSUE THREAD

**Issue by poggenpower** [aquasecurity/postee#265]
From https://github.com/aquasecurity/postee/blob/main/go.mod#L3 postee requires go version 1.17, but 
https://github.com/aquasecurity/postee/blob/main/Dockerfile#L1,
https://github.com/aquasecurity/postee/blob/main/Dockerfile.ui#L9 and
https://github.com/aquasecurity/postee/blob/main/ui/backend/go.mod#L3

pointing to go 1.16 or older.

**Comment by simar7** [comment]
thanks for the catch @poggenpower - we'll fix it soon
