### ISSUE TITLE
Running with docker compose won't refresh postee

### ISSUE THREAD

**Issue by poggenpower** [aquasecurity/postee#268]
when running  postee and posteeui via docker compose, the `/server` path get mounted to a persistent volume. 
As the postee binary lives in this directory it won't get updated if you build a new version. Even if your new container contains the new postee binary, the mount of `/server` at runtime will hide the updated version and the postee version placed in the volume at the first creation of the volume will be started. 

The postee binar should live outside of the mount/volume.

**Comment by simar7** [comment]
thanks - if you'd like to submit a PR we can take a look at it.

**Comment by simar7** [comment]
can we close this now @poggenpower?

**Comment by simar7** [comment]
Please reopen if needed.
