### ISSUE TITLE
Access environment variables in rego template

### ISSUE THREAD

**Issue by lorsal** [aquasecurity/postee#269]
I tried accessing environment variables via opa.runtime(), but that does not work in Postee, I assume because opa is used as go library? Is there another way to access env variables?

**Comment by simar7** [comment]
hi @lorsal could you explain what's your use case with an example? If you're trying to use `opa.runtime()` within your template I don't see why using the Go library should make a difference.

An example is: `opa.runtime()["env"]["MYVAR"]` to access  `MYVAR`

**Comment by lorsal** [comment]
Hi @simar7 
We would like to include additional information via environment variables, e.g. a grace period for image compliance and the cluster name that the image is running on. This information could then be set at one place in the source code before rollout.
Using my rego templatel, I am able to access environment variables on my local machine with opa.runtime(), but it does not work in the Postee pod with the same template. Does it work on your side?

**Comment by lorsal** [comment]
On my local machine, I used opa eval for testing.

**Comment by simar7** [comment]
hi @lorsal thanks for your patience. I just validated that indeed this is a limitation of the OPA Go SDK as I couldn't manage to run it either locally. Someone had already asked about this in the OPA Slack channel https://openpolicyagent.slack.com/archives/CBR63TK2A/p1637682347153700 - it is not supported by the Go SDK today.

I've asked the OPA folks on Slack to see if I can contribute this change so the Go SDK can access the `opa.runtime()` data. Will update back if I hear anything.

**Comment by simar7** [comment]
hi @lorsal - looks like access to `opa.runtime()` was merged in OPA v0.36. I've bumped up our OPA dependency to that and in the next release of Postee this should be available.

**Comment by simar7** [comment]
hi @lorsal - I just released https://github.com/aquasecurity/postee/releases/tag/v2.1.0 could you try it out?

**Comment by simar7** [comment]
v2.2.0https://github.com/aquasecurity/postee/releases/tag/v2.2.0  is now released which has an updated OPA - please let us know if you're still facing an issue by reopening.  Thanks.
