### ISSUE TITLE
vuls-html.rego does not evaluate whether or not malware/sensitive data was found, only whether it was scanned for

### ISSUE THREAD

**Issue by lorsal** [aquasecurity/postee#270]
I believe the following code in vuls-html.rego is supposed to evaluate whether malware or sensitive data were found:

by_flag(
     "Malware found: Yes",
     "Malware found: No",
     input.scan_options.scan_malware #reflects current logic
    ),
	by_flag(
	 "Sensitive data found: Yes",
     "Sensitive data found: No",
     input.scan_options.scan_sensitive_data #reflects current logic
	),

It seems that this only checks whether or not it was scanned for, so this evaluates to true for every image if those scan options are active, even when the image has no malware or sensitive data.

**Comment by simar7** [comment]
The definition of `by_flag` is here: https://github.com/aquasecurity/postee/blob/0748851b7b33a93fb1e9fbe7dc74343e85ff1009/rego-templates/common/common.rego#L15-L20



It should evaluate to a or b depending upon if the result of the boolean flag was true (set to a), false (set to b). https://play.openpolicyagent.org/p/BbuYjeHMhf

**Comment by lorsal** [comment]
Hi @simar7 
yes, its just that the property input.scan_options.scan_sensitive_data/scan_malware is true if the corresponding scanning option is activated in the GUI (see screenshot). This property is not suitable to check whether or not there was, in fact, sensitive data or malware found. But that seems to be the purpose since it says "Sensitive data/Malware found: Yes/No"
When deactivating the options in the GUI, the template fails with a result not found error, since the properties input.scan_options.scan_sensitive_data/scan_malware are then not present in the result JSON at all. 
Please correct me if I am mistaken.
So for us, it is relevant whether that issue is known and worked on, otherwise we will include it in our own template customization work.
![scanoption](https://user-images.githubusercontent.com/79901914/152499460-17f99062-6cf4-493b-925d-4a0d55a716f1.PNG)
.

**Comment by simar7** [comment]
hi @lorsal - I'm not too familiar with the UI integration but I will ask internally and get back to you on this. Thanks.

**Comment by lorsal** [comment]
hi @simar7 thank you. We have adapted the template to address this, so it is solved for us.
