### ISSUE TITLE
Few Errors on Kubernetes installation. 

### ISSUE THREAD

**Issue by velizmiguel** [aquasecurity/postee#273]
Hello all, i tried running postee on my kubernetes cluster following the steps here: https://github.com/aquasecurity/postee/tree/main/deploy/kubernetes

And im getting a few errors: 

- Anytime i try changing something using the UI i get: Unauthorized
- The UI shows the changes but when i try them the backend still pointing to old config. 
- Sometimes i get the following error in the ui:  `open /server/database/webhooks.db: permission denied `
- The logs show the following error: Can not initialize template slack-template: 1 error occurred during loading: open rego-templates/custom/lost+found: permission denied

Also i tried the helm chart, and it doesnt work at all, it doesnt create anything.

**Comment by krol3** [comment]
Hi @velizmiguel !  I will review this issue about manifest. Also, the helm chart was updated recently.

**Comment by krol3** [comment]
@velizmiguel The PR was merged! any problem about this issue send a message here.
