### ISSUE TITLE
Postee customized integration with SMTP Relay Service

### ISSUE THREAD

**Issue by sandip4aqua** [aquasecurity/postee#283]
We would require below feature enhancement for Postee
-->Integration with custom smtp replay service by providing hostname and port number
-->no user authentication.

**Comment by simar7** [comment]
hi @sandip4aqua - this already exists today https://github.com/aquasecurity/postee/blob/main/cfg.yaml#L74-L89

**Comment by simar7** [comment]
Please reopen if issue is still unresolved. Thanks.

**Comment by sandip4aqua** [comment]
The Customer is looking to have the user/pass not a requirement for their email smtp integration.
Since we don’t provide user and password, the connection parameters from Postee would only be the following:
•	SMTP server: hostname or IP address
•	Port number: currently it is using the default 25 
 On Aqua side there is an internal process that we have to follow with the Messaging Team; they have to set us up to use the SMTP service in their end:
•	They need to register our application node information as connection originator
o	With this I am only allowed to send messages from a specific application node
•	They have to setup an account for the Postee “sender” parameter:
o	For example the value of the sender parameter in this case would be: [mailbox.aquacsp.dev@registeredonpremdomain.com](mailto:mailbox.aquacsp.dev@registeredonpremdomain.com)
