### ISSUE TITLE
Filtering Severity for Slack

### ISSUE THREAD

**Issue by sandip2503** [aquasecurity/postee#333]
One of our customer wants filtering and sending only criticals and high severity compliance on slack channel. Can you please help.

**Comment by DmitriyLewen** [comment]
Hello @sandip2503 
Tnanks for your interest to Postee!

Routes field in config file has `input` and `input-files` fields. Use these fields for filter message. You can create new [REGO rule](https://www.openpolicyagent.org/docs/v0.37.2/policy-language/) or use examples from `rego-filters` folder. [Read more about using REGO rules for Postee here. ](https://github.com/aquasecurity/postee/tree/main#routes).

Regards, Dmitriy

**Comment by simar7** [comment]
hi @sandip2503 please reopen if the issue is still not resolved. Thanks.
