### ISSUE TITLE
Postee Kubernetes installation not working

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/postee#348]
## Description

I have tried to install the Helm Chart but I think it is missing several resources e.g. it is currently not installing the postee deployment but also other resources that are in the `pure` Kubernertes manifests are not getting installed.

So I tried to follow this README and install postee directly through the YAML
https://github.com/aquasecurity/postee/blob/main/deploy/kubernetes/README.md

The thing is that the pod does not get spun up -- the deployment is kinda stuck, not showing any logs or events that could give a hint.

It says/it is expected that the following resources are going to be installed:
![Screenshot 2022-04-07 at 14 40 30](https://user-images.githubusercontent.com/33576047/162217218-19cfdf83-353b-4653-bbab-d31350c3da4c.png)

However, the PVs are not getting spun up so the pods cannot attach to them -- I think that was the problem.

So I tried the same installation on a larger cluster on GKE. However, the postee-ui pod cannot attach to the PVCs because the postee-0 pod already attached to them.
![Screenshot 2022-04-08 at 10 52 39](https://user-images.githubusercontent.com/33576047/162412475-9c8a67db-fef8-4e67-bfd7-cd07a46e83cf.png)

here are the events of the postee-0 pod:
![Screenshot 2022-04-08 at 10 55 27](https://user-images.githubusercontent.com/33576047/162412765-3b55a466-7b29-4a77-bbd0-c1da8b086fee.png)

I am wondering why the pods try to attache to the same PVs? The other PVs referenced in the postee-0 pod get created but nothing attaches to them
![Screenshot 2022-04-08 at 10 53 27](https://user-images.githubusercontent.com/33576047/162412353-75d74f58-667b-40ca-8aa2-b5a6a6ae3819.png)
![Screenshot 2022-04-08 at 10 44 28](https://user-images.githubusercontent.com/33576047/162412114-490119d1-f727-4df1-b525-417d1ef758dd.png)

Also, where does the postee-0 pod deployment live?

**Comment by simar7** [comment]
@krol3 could you look into this?

**Comment by krol3** [comment]
@simar7 @AnaisUrlichs working in this issue with this PR https://github.com/aquasecurity/postee/pull/349

**Comment by krol3** [comment]
@AnaisUrlichs I tested the [manifest](https://github.com/aquasecurity/postee/blob/main/deploy/kubernetes/postee.yaml) and works for me in a eks and kind cluster. Could you give more details about the k8s environment and version? 

<img width="1133" alt="Screen Shot 2022-04-12 at 20 51 07" src="https://user-images.githubusercontent.com/8355621/163083740-60626461-df0e-43ce-839f-c85a94fb2b15.png">

**Comment by simar7** [comment]
@AnaisUrlichs I just merged the PR that @krol3 created to fix this. Could you confirm is the latest main branch has resolved your issue?

**Comment by simar7** [comment]
Please reopen if issue still persists. Thanks.

**Comment by jessequinn** [comment]
on GKE im getting " Multi-Attach error for volume"
