### ISSUE TITLE
postee-pv.yml names do not match what is actually called in the postee.yml

### ISSUE THREAD

**Issue by danekantner** [aquasecurity/postee#374]
The names in the deployment reference claimName: postee-config-postee-0 and postee-db-postee-0 but they are called postee-pv and postee-config in the postee-pv.yml -- the two names should match so they should be updated to be the same. 

https://github.com/aquasecurity/postee/blob/9c44eaeac73a284b96b767c6e0892d9f0060f439/deploy/kubernetes/hostPath/postee-pv.yaml#L6

**Comment by krol3** [comment]
Hi @danekantner, the **names** of the Persistence Volumes are not used when you do the claim in the pods, the PVC only bind the capacity storage and the accessMode. See the sample here https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

**Comment by krol3** [comment]
PR merged! Any doubt please share your comments here
