### ISSUE TITLE
Add information about optional/required fields in Actions documentation

### ISSUE THREAD

**Issue by simar7** [aquasecurity/postee#380]
The documentation currently lists fields that our Actions accept but doesn't always list which field is Optional vs. Required. This information however is available within the comments for each Action in the sample cfg.yaml file we used to have: https://github.com/aquasecurity/postee/blob/main/cfg.yaml

Documentation exists here: https://github.com/aquasecurity/postee/blob/main/docs/actions.md

Acceptance Criteria:
* Clearly document each field for every Action to be Required or Optional as a separate column within the same table of all fields.

**Comment by souravsk** [comment]
hi @simar7 do I have to make the changes in this table: https://github.com/aquasecurity/postee/blob/main/docs/actions.md
because as I checked the table available on this page already has the optional and required mention already.
if not then let me know i can work on this issue

**Comment by simar7** [comment]
> hi @simar7 do I have to make the changes in this table: https://github.com/aquasecurity/postee/blob/main/docs/actions.md
> 
> because as I checked the table available on this page already has the optional and required mention already.
> 
> if not then let me know i can work on this issue
> 
> 

Yes that's right. We need a new column for every table in this markdown that clearly explains if it is a required field or not.

**Comment by souravsk** [comment]
okay i can do that

**Comment by souravsk** [comment]
hi, @simar7  what will the name of the column I have a preview if that is what you want I can move on.
### Before
![aq2](https://user-images.githubusercontent.com/33636054/190401553-2cb30ce0-dda2-45a0-9745-5cf937d5af62.png)

### After
![aq1](https://user-images.githubusercontent.com/33636054/190401579-408bd505-341f-40b7-aaa1-f9f746477ec8.png)

Please let me know if I have made any mistakes to understand this issue.

**Comment by souravsk** [comment]
That will be very simple to understand. Nice I will do that.

**Comment by souravsk** [comment]
@simar7 should I also remove the "Required" and "Optional" that are written in the usage or I should leave it like that

**Comment by simar7** [comment]
> @simar7 should I also remove the "Required" and "Optional" that are written in the usage or I should leave it like that

That's part of the task. Ideally like you said, need a single column to define requirement to be yes or no.

**Comment by souravsk** [comment]
Hey @simar7 i have created the PR you can check #462

**Comment by simar7** [comment]
Fixed with #462
