### ISSUE TITLE
Idempotency in Jira Issues & Developer Guide

### ISSUE THREAD

**Issue by Ipuvi** [aquasecurity/postee#387]
Hi Team
Does this takes care of Idempotency while creating Jira issues?
Also, is there a developer guide one could follow to integrate with our existing Trivy Vulnerability Scans?

**Comment by simar7** [comment]
Hi @Ipuvi 

For your first question, yes you can enable the `unique-message-props` value. This is documented here https://aquasecurity.github.io/postee/routes/#plugins

Your second question brings up a great point that's a valid use case. I will document this in a walkthrough/guide shortly.
