### ISSUE TITLE
Ingress template not compatible with k8s 1.22+

### ISSUE THREAD

**Issue by jrx-sjg** [aquasecurity/postee#477]
## Ingress template not compatible with k8s 1.22

```
[WARNING] templates/ingress.yaml: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

## Additional details (environment setup, networking info...):
Changing the apiVersion on Ingress template to use buildIn .Capabilities.KubeVersion.GitVersion >= 1.19 solves the issue.

**Comment by simar7** [comment]
Closed with https://github.com/aquasecurity/postee/pull/559
