### ISSUE TITLE
Add support in OpsGenie 

### ISSUE THREAD

**Issue by amirgabrieli** [aquasecurity/postee#48]
We need to add support in OpsGenie. Similar functionality as for ServiceNow. 
BTW, we already have Golang code that sends tickets to OpsGenie

**Comment by afdesk** [comment]
hello @amirgabrieli !
I want to resolve this issue.
Would you mind showing Golang code that sends tickets to OpsGenie?
Thanks!

**Comment by amirgabrieli** [comment]
Hi,

The Golang is part of a private repo. However, I can send you the golang files to your email.  LMK
