### ISSUE TITLE
Add curl and jq to the postee release build

### ISSUE THREAD

**Issue by Urth** [aquasecurity/postee#548]
# Description
In https://github.com/aquasecurity/postee/commit/7bfaf1d26d8604cf7c965c073b788db6d6630182 the curl and jq commands were added to the default Dockerfile. But the Dockerfile.release used for the docker.io builds only has wget.

It would be very convenient to have both available in the official release.

# Use Case
An exec action to manipulate json and post an extract to a url.

# Acceptance Criteria
Would allow posting trivy operator reports to defectdojo with the official postee release.

**Comment by simar7** [comment]
PRs welcome!

**Comment by BenjaminHerbert** [comment]
@simar7 I also have this requirement - I created #578 for it.
