### ISSUE TITLE
Make Postee able to upload Sbom to Dtrack 

### ISSUE THREAD

**Issue by mcbenjemaa** [aquasecurity/postee#575]
# Description

I'm using trivy-operator to scan vuln, and then I use a custom component to upload the results to Dtrack.
it would be great, if Postee can integrate this feature.

# Use Case

As a Platform engineer 
I would like to use trivy-operator to scan images with Sbom format, 
and then upload results to Dtrack
so that I can accomplish centralised visibility.

# Acceptance Criteria

When feature upload to Dtrack is implemented, I will be able to use trivy-operator and postee only to upload the scan results

### Hints 

- dtrack client http://github.com/nscuro/dtrack-client

**Comment by DmitriyLewen** [comment]
added in v2.14.0 (https://github.com/aquasecurity/postee/pull/594)
