### ISSUE TITLE
Add trivy operator postee template for jira

### ISSUE THREAD

**Issue by martijnvdp** [aquasecurity/postee#598]
# Description
Add trivy operator postee template for jira, as the current jira templates dont work with the output of the trivy operator

# Use Case
As a User of the trivy operator
I would like to see a template that can be used for automatically creating jira tickets from the output of the trivy operator data,
with detailed info about the findings including the links to the CVE-xxx

**Comment by martijnvdp** [comment]
copied the existing jira template and made it suitable for the trivy operator
and fixed the colomns and added summary with totals
![image](https://github.com/aquasecurity/postee/assets/73637849/825a2608-2cb6-44ff-9479-417d692e0c60)

**Comment by DmitriyLewen** [comment]
added in `v2.14.0` (#595)
