### ISSUE TITLE
Email notifications: SMTP HELO check rejects "localhost"

### ISSUE THREAD

**Issue by roeelivaqua** [aquasecurity/postee#602]
Customer is trying to Integrate their SMTP server to Aqua but the test fails with the following Aqua GUI ERROR:

504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname

**Failed to test notification output: 504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname
[Postee] failed to send email: 504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname**

SMTP Server Log:
**Jul 11 10:35:53 dz-smtp-01 postfix/submission/smtpd[12073]: NOQUEUE: reject: RCPT from [ec2-3-69-237-88.eu-central-1.compute.amazonaws.com](http://ec2-3-69-237-88.eu-central-1.compute.amazonaws.com/)[3.69.237.88]: 504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname; from=[br_as@br.de](mailto:br_as@br.de)to=[christian.heigl@br.de](mailto:christian.heigl@br.de) proto=ESMTP helo=<localhost>**

Sending localhost is the default behaviour of the net/smtp package:
[smtp package - net/smtp - Go Packages](https://pkg.go.dev/net/smtp#Client.Hello). This needs to be changed.

**Comment by poggenpower** [comment]
Beside using the FQDN if the host sending the message, it should be configurable. esp. if postee is running behind a firewall/NAT-GW you want specify the public DNS to be most friendly to the SMPT Server and hide internal details.

**Comment by afdesk** [comment]
hi @roeelivaqua! 
I'm on this task right now. 

it makes sence to update `localName`, but I'd lie to reproduce the error at first.

**Comment by poggenpower** [comment]
@afdesk 

I was able to reproduce it with a postfix using:

`smtpd_helo_restrictions = permit_mynetworks, reject_non_fqdn_helo_hostname, reject_invalid_helo_hostname, permit`

as config, where is `reject_non_fqdn_helo_hostname` the important part.

**Comment by afdesk** [comment]
> I was able to reproduce it with a postfix using:

@poggenpower it's great. thanks 
will try it

**Comment by afdesk** [comment]
@poggenpower I'm trying to run a custom smtp server locally. 
for tests I uses next repo: https://github.com/afdesk/docker-postfix

I've updated a config https://github.com/afdesk/docker-postfix/commit/357d9dc7711c7555182fa5dcf981f70a8d58180b

but after build and run a container I still can send emails:
```sh
$ DOCKER_BUILDKIT=1 docker build -t customsmtp:1 .
$ docker run -it -p 5587:587 -e "ALLOWED_SENDER_DOMAINS=mycompany.com" customsmtp:1
```

It seems I missed another settings...

@poggenpower 
Do you have any scripts for run smtp? thanks

**Comment by mulan04** [comment]
I double-checked the issue reproduction using the  afdesk/docker-postfix you mentioned
As documented
[https://github.com/afdesk/docker-postfix#overriding-specific-postfix-settings](url)
use
`... -e "POSTFIX_smtpd_helo_restrictions=reject_invalid_helo_hostname,reject_non_fqdn_helo_hostname"   ...`
to enable the FQDN check of the mail client

**Comment by afdesk** [comment]
@mulan04 thanks! it look really useful.
