### ISSUE TITLE
create release using goreleaser

### ISSUE THREAD

**Issue by krol3** [aquasecurity/postee#71]
I´m trying to create a release with github actions
I have some errors to build the main class

Here the error: [Branch-release-test](https://github.com/krol3/alm-integration/runs/1591791175?check_suite_focus=true)

**Comment by jerbia** [comment]
@afdesk can you help @krol3 with the issue?

**Comment by afdesk** [comment]
@krol3 It seems like github actions (or goreleaser) don't see `GOPATH`.
Can you show a settings file (`.github/workflows/release.yml`)?
for my tests. thanks!

**Comment by krol3** [comment]
I will review it

**Comment by afdesk** [comment]
hi @krol3!
Can you help with one moment, please?

It seems like I found a problem.
Now ALM integration uses `make` without go modules. 

Would you check your goreleaser script with `GO111MODULE=off` and without `go mod download`?

Thanks!

**Comment by krol3** [comment]
Now, It's working please take a look: https://github.com/krol3/alm-integration/actions/runs/551680167

**Comment by krol3** [comment]
For your review @jerbia and @afdesk . Here are the following steps to create a release. I will update the docker to use the gorelease too.
```
git tag -a v1.1.3 -m "Using go release v1.1.3"
git push origin v1.1.3
```
https://github.com/krol3/alm-integration/releases/tag/v1.1.3
https://github.com/krol3/alm-integration/actions/runs/555014086

**Comment by krol3** [comment]
Closing this issue, already merged.
