### ISSUE TITLE
Support Docker Labels for Integration Settings value

### ISSUE THREAD

**Issue by ericgomes56** [aquasecurity/postee#73]
Please extend support for Docker Labels as criteria for routing risk assessments.  

There is a need to use Docker image metadata or labels that can create/ingest to route traffic to specific JIRA boards based on metadata from the docker image itself -- rather than mapping docker image names to specific teams.

We have upwards of 10 teams that manage a dozen or more different docker images. We don't necessarily want to maintain multiple configs for the webhook specifying exactly which teams manage which docker images i.e (commerce team handles these image names lifeway/orderentry:*, lifeway/purchaseapi:*, etc.).

**Comment by jerbia** [comment]
@ericgomes56 currently the image label information is not sent via webhook.

Are they familiar with the support of user emails that they can use? Create an Application Context, assign it to a user email and ALM Integration receives the email address as part of the Webhook. Would that help?

**Comment by ericgomes56** [comment]
@jerbia I will follow up with any concerns early next week but that approach makes a lot of sense.

**Comment by ericgomes56** [comment]
@jerbia can we add an Application Scope to the JIRA integration?

Ideally what would happen if using something like an Application Scope is we define all the Application Scope, generally going to be one per development team.  Inside each Application Scope, we would define the namespaces that each team owns. Then, once the ALM (Postee) webhook kicks off, it would see which scope that image falls into and route it to the appropriate JIRA board.  So, even if we had to have a JIRA integration defined per Application Scope that would be better than us trying to define it per image name and modifying the cfg.yaml which the Postee pod would need to be restarted.

**Comment by ericgomes56** [comment]
@jerbia do you think we can add flexibility to use the Application Scope in the cfg.yaml? This is for Lifeway.

**Comment by jerbia** [comment]
Yes. We have support for application scope owner in the email integration.

To which other integration do you want to add support for app scope owner?

**Comment by ericgomes56** [comment]
@jerbia for the JIRA integration.  Lifeway has stopped working on Postee until we can get Application Scope support for it.

**Comment by jerbia** [comment]
@afdesk can you add support for JIRA assignee to be based on the application owner email?
Same as we did for email integration.

**Comment by nikolakresic** [comment]
I have question here.
We are also interested in this functionality but i dont see how this could work for multiple users sharing the scope in such a way that they see some resources and it overlaps, so i have 2 or more scoped users who see the same resource, whatever that is - which one will be selected and pushed to JIRA ?

Can we have something like an internal Aqua label that we apply to something (registry ? host ? enforcer ?) and postee picks this up and based on the label value (email, username) pushes this to JIRA and JIRA assigns this properly ?

**Comment by jerbia** [comment]
@nikolakresic  Once you scan an image that is member of multiple scopes, Postee will be triggered with the list of all owners of the application scopes that image is member of (meaning, an array of emails).

Right now the Application Scope email address is only used with the Postee "email" provider. In case of multiple email addresses, Postee will send an email to these multiple email addresses.

For JIRA the issue might be that JIRA does not support multiple email addresses - only one email should be assigned.

Another option is to support taking the "aqua label" from the image and use it for the JIRA integration.
Would that help?
Note that there is no mechanism that automatically assigns Aqua Labels to images - this will need to be done manually, so not sure if this will help.

**Comment by nikolakresic** [comment]
@jerbia maybe not manually but through API calls, so i can script it somehow ?

while were talking, is there a way for Aqua to read "properties" from artifactory ? we dont need to keep ownership info directly in Aqua if Aqua can pull this from somewhere else ?

**Comment by jerbia** [comment]
@nikolakresic we've added support for JIRA assignee to get the email from the Application Context in Aqua.
The challenge is that in case of multiple emails in the application context, JIRA will just get the first email address as asignee.

As suggested, we can also support to consume the Aqua Labels assigned to the image, and used it as the JIRA assignee. 
Is it something you'll be interested in?

**Comment by jerbia** [comment]
Hi @nikolakresic please look at Postee v2 - it now has capabilities to create multiple routes. 
Each route can be configured to open JIRA ticket for different user based on the message input parameters. 

Please look at this new functionality and let us know if additional capabilities are needed.

Closing this issue for now.
