### ISSUE TITLE
Add Support for specific Vulnerability Severity

### ISSUE THREAD

**Issue by ericgomes56** [aquasecurity/postee#96]
@jerbia do you think we could add support for a specific vulnerability severity as part of a key in the cfg.yaml?  Something like 'Policy-Vulnerability-Level'?  'Policy-Min-Vulnerability' does a severity range but 'Policy-Vulnerability-Level' does exactly only the severity level specified as the value.  Our customer would love this flexibility as they use JIRA in their daily workflows.

**Comment by jerbia** [comment]
Not sure I understand the use case.

Assume you have specific vulnerability set, like "medium", but image has low and high - so you don't want to get any notification?

Now assume you have the configuration set to "medium", and image has medium and high - in this case you do want to get notification that will include all the vulnerabilities?

**Comment by ericgomes56** [comment]
@jerbia yes, that is correct.

**Comment by jerbia** [comment]
You can do it with the new support to OPA policy rules.

Add this to the cfg.yaml JIRA section:
  Policy_OPA: ["/config/policy.rego"]

Create the policy.rego file with this content:

package postee
default allow = false
allow {
    input.vulnerability_summary.critical=0
    input.vulnerability_summary.high=0
    input.vulnerability_summary.medium>0
}

This will trigger the JIRA only if medium vulnerabilities is above 0 and high and critical is 0.

Note that you need to mount the policy.rego to /config directory in the image.
